FROM public.ecr.aws/lambda/python:3.7

COPY object_detection.py config.py detect.py upload.py handler.py delete_image.py remove_tag.py search.py requirements.txt ./
COPY yolo_configs ./yolo_configs

RUN python3.7 -m pip install -r requirements.txt -t .

USER python
# Command can be overwritten by providing a different command in the template directly.
CMD ["handler.lambda_handler"]
